// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api/hello/demo.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Demo service

func NewDemoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Demo service

type DemoService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type demoService struct {
	c    client.Client
	name string
}

func NewDemoService(name string, c client.Client) DemoService {
	return &demoService{
		c:    c,
		name: name,
	}
}

func (c *demoService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Demo.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Demo service

type DemoHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterDemoHandler(s server.Server, hdlr DemoHandler, opts ...server.HandlerOption) error {
	type demo interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type Demo struct {
		demo
	}
	h := &demoHandler{hdlr}
	return s.Handle(s.NewHandler(&Demo{h}, opts...))
}

type demoHandler struct {
	DemoHandler
}

func (h *demoHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.DemoHandler.Hello(ctx, in, out)
}
